-- Database-driven runway visual guidance profiles for replay training overlays.
-- Safe to re-run. These profiles are presentation/training aids, not replay facts.

CREATE TABLE IF NOT EXISTS ipca_runway_visual_guidance_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  airport_icao VARCHAR(8) NOT NULL,
  runway_ident VARCHAR(16) NOT NULL,
  runway_name VARCHAR(64) NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  threshold_lat DECIMAL(10,7) NOT NULL,
  threshold_lon DECIMAL(10,7) NOT NULL,
  threshold_elevation_ft DECIMAL(8,1) NULL,
  runway_true_heading_deg DECIMAL(6,2) NOT NULL,
  runway_length_ft DECIMAL(8,1) NULL,
  runway_width_ft DECIMAL(7,1) NULL,
  papi_enabled TINYINT(1) NOT NULL DEFAULT 1,
  papi_side ENUM('left','right') NOT NULL DEFAULT 'left',
  papi_lateral_offset_ft DECIMAL(7,1) NOT NULL DEFAULT 300.0,
  papi_distance_from_threshold_ft DECIMAL(7,1) NOT NULL DEFAULT 1000.0,
  papi_light_spacing_ft DECIMAL(6,1) NOT NULL DEFAULT 20.0,
  glide_path_angle_deg DECIMAL(5,2) NOT NULL DEFAULT 3.00,
  threshold_crossing_height_ft DECIMAL(6,1) NOT NULL DEFAULT 50.0,
  source VARCHAR(64) NOT NULL DEFAULT 'manual',
  review_status ENUM('draft','reviewed','approved') NOT NULL DEFAULT 'draft',
  notes VARCHAR(512) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_ipca_runway_visual_guidance (airport_icao, runway_ident),
  KEY idx_ipca_runway_visual_guidance_airport (airport_icao, active),
  KEY idx_ipca_runway_visual_guidance_active (active, papi_enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Runway-specific visual glidepath/PAPI replay training overlay profiles.';

INSERT INTO ipca_runway_visual_guidance_profiles (
  airport_icao,
  runway_ident,
  runway_name,
  active,
  threshold_lat,
  threshold_lon,
  threshold_elevation_ft,
  runway_true_heading_deg,
  runway_length_ft,
  runway_width_ft,
  papi_enabled,
  papi_side,
  papi_lateral_offset_ft,
  papi_distance_from_threshold_ft,
  papi_light_spacing_ft,
  glide_path_angle_deg,
  threshold_crossing_height_ft,
  source,
  review_status,
  notes
) VALUES
  (
    'KTRM',
    '17',
    'Jacqueline Cochran Regional RWY 17',
    1,
    33.6391447,
    -116.1564066,
    -114.4,
    180.00,
    8500.0,
    150.0,
    1,
    'left',
    300.0,
    1000.0,
    35.0,
    3.00,
    51.0,
    'faa_nfdc_seed',
    'reviewed',
    'FAA/NFDC: P4L, 3.00 degree glide path, threshold 33-38-20.921N 116-09-23.0638W.'
  ),
  (
    'KTRM',
    '35',
    'Jacqueline Cochran Regional RWY 35',
    1,
    33.6157854,
    -116.1564150,
    -134.4,
    0.00,
    8500.0,
    150.0,
    1,
    'left',
    300.0,
    1000.0,
    35.0,
    3.00,
    52.0,
    'faa_nfdc_seed',
    'reviewed',
    'FAA/NFDC: P4L, 3.00 degree glide path, threshold 33-36-56.8274N 116-09-23.0938W; unusable beyond 8 NM due terrain.'
  )
ON DUPLICATE KEY UPDATE
  runway_name = VALUES(runway_name),
  active = VALUES(active),
  threshold_lat = VALUES(threshold_lat),
  threshold_lon = VALUES(threshold_lon),
  threshold_elevation_ft = VALUES(threshold_elevation_ft),
  runway_true_heading_deg = VALUES(runway_true_heading_deg),
  runway_length_ft = VALUES(runway_length_ft),
  runway_width_ft = VALUES(runway_width_ft),
  papi_enabled = VALUES(papi_enabled),
  papi_side = VALUES(papi_side),
  papi_lateral_offset_ft = VALUES(papi_lateral_offset_ft),
  papi_distance_from_threshold_ft = VALUES(papi_distance_from_threshold_ft),
  papi_light_spacing_ft = VALUES(papi_light_spacing_ft),
  glide_path_angle_deg = VALUES(glide_path_angle_deg),
  threshold_crossing_height_ft = VALUES(threshold_crossing_height_ft),
  source = VALUES(source),
  review_status = VALUES(review_status),
  notes = VALUES(notes),
  updated_at = CURRENT_TIMESTAMP;
