-- AI Manual Change Assistant (additive foundation).
-- Uploaded source bodies remain in private storage; only metadata and evidence excerpts are stored here.

CREATE TABLE IF NOT EXISTS ipca_manual_ai_projects (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  project_uuid CHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'draft' COMMENT 'draft | ready | analyzing | completed | failed | archived',
  source_fingerprint CHAR(64) NULL,
  scope_fingerprint CHAR(64) NULL,
  created_by INT NOT NULL,
  updated_by INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_imap_uuid (project_uuid),
  KEY idx_imap_owner_status (created_by, status, updated_at),
  CONSTRAINT fk_imap_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_imap_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ipca_manual_ai_sources (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  project_id BIGINT UNSIGNED NOT NULL,
  source_uuid CHAR(36) NOT NULL,
  source_type VARCHAR(24) NOT NULL DEFAULT 'text' COMMENT 'text | txt | pdf | docx',
  original_name VARCHAR(255) NULL,
  mime_type VARCHAR(127) NULL,
  storage_path VARCHAR(500) NULL,
  title VARCHAR(255) NOT NULL,
  issuer VARCHAR(255) NULL,
  reference_code VARCHAR(191) NULL,
  effective_date DATE NULL,
  content_sha256 CHAR(64) NOT NULL,
  byte_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
  extraction_status VARCHAR(32) NOT NULL DEFAULT 'ready' COMMENT 'ready | unsupported | failed',
  metadata_json JSON NULL,
  uploaded_by INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_imas_uuid (source_uuid),
  UNIQUE KEY uk_imas_project_hash (project_id, content_sha256),
  KEY idx_imas_project (project_id, created_at),
  CONSTRAINT fk_imas_project FOREIGN KEY (project_id) REFERENCES ipca_manual_ai_projects(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_imas_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ipca_manual_ai_version_scopes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  project_id BIGINT UNSIGNED NOT NULL,
  book_version_id BIGINT UNSIGNED NOT NULL,
  version_content_hash CHAR(64) NOT NULL,
  lifecycle_status_snapshot VARCHAR(32) NOT NULL,
  selected_by INT NOT NULL,
  selected_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_imavs_project_version (project_id, book_version_id),
  KEY idx_imavs_version (book_version_id),
  CONSTRAINT fk_imavs_project FOREIGN KEY (project_id) REFERENCES ipca_manual_ai_projects(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_imavs_version FOREIGN KEY (book_version_id) REFERENCES ipca_publishing_book_versions(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_imavs_selected_by FOREIGN KEY (selected_by) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ipca_manual_ai_requirements (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  project_id BIGINT UNSIGNED NOT NULL,
  source_id BIGINT UNSIGNED NOT NULL,
  requirement_key VARCHAR(191) NOT NULL,
  requirement_text TEXT NOT NULL,
  normalized_text TEXT NOT NULL,
  source_evidence_json JSON NOT NULL,
  requirement_hash CHAR(64) NOT NULL,
  extraction_method VARCHAR(24) NOT NULL DEFAULT 'deterministic',
  ai_run_id VARCHAR(191) NULL,
  confidence DECIMAL(5,4) NOT NULL DEFAULT 0.5000,
  status VARCHAR(24) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_imar_project_hash (project_id, requirement_hash),
  KEY idx_imar_source_status (source_id, status),
  CONSTRAINT fk_imar_project FOREIGN KEY (project_id) REFERENCES ipca_manual_ai_projects(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_imar_source FOREIGN KEY (source_id) REFERENCES ipca_manual_ai_sources(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ipca_manual_ai_content_chunks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  project_id BIGINT UNSIGNED NOT NULL,
  book_version_id BIGINT UNSIGNED NOT NULL,
  section_id BIGINT UNSIGNED NOT NULL,
  block_id BIGINT UNSIGNED NOT NULL,
  block_content_hash CHAR(64) NOT NULL,
  chunk_hash CHAR(64) NOT NULL,
  chunk_index INT UNSIGNED NOT NULL DEFAULT 0,
  stable_anchor VARCHAR(191) NOT NULL,
  section_reference VARCHAR(191) NOT NULL,
  chunk_text MEDIUMTEXT NOT NULL,
  normalized_text MEDIUMTEXT NOT NULL,
  keywords_json JSON NULL,
  embedding_model VARCHAR(64) NULL,
  embedding_content_hash CHAR(64) NULL,
  embedding_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_imacc_project_block_chunk (project_id, block_id, chunk_index),
  KEY idx_imacc_project_version (project_id, book_version_id),
  KEY idx_imacc_hash (chunk_hash),
  CONSTRAINT fk_imacc_project FOREIGN KEY (project_id) REFERENCES ipca_manual_ai_projects(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_imacc_version FOREIGN KEY (book_version_id) REFERENCES ipca_publishing_book_versions(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_imacc_section FOREIGN KEY (section_id) REFERENCES ipca_publishing_book_sections(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_imacc_block FOREIGN KEY (block_id) REFERENCES ipca_publishing_book_blocks(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ipca_manual_ai_findings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  project_id BIGINT UNSIGNED NOT NULL,
  requirement_id BIGINT UNSIGNED NULL,
  finding_key CHAR(64) NOT NULL,
  finding_type VARCHAR(32) NOT NULL COMMENT 'impact | consistency | duplication | conflict',
  action_classification VARCHAR(32) NOT NULL COMMENT 'add | replace | cross_reference | investigate | no_change',
  confidence DECIMAL(5,4) NOT NULL DEFAULT 0.5000,
  title VARCHAR(255) NOT NULL,
  rationale TEXT NOT NULL,
  evidence_json JSON NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'proposed',
  assigned_reviewer_id INT NULL,
  ai_run_id VARCHAR(191) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_imaf_project_key (project_id, finding_key),
  KEY idx_imaf_project_status (project_id, status, finding_type),
  CONSTRAINT fk_imaf_project FOREIGN KEY (project_id) REFERENCES ipca_manual_ai_projects(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_imaf_requirement FOREIGN KEY (requirement_id) REFERENCES ipca_manual_ai_requirements(id) ON DELETE SET NULL ON UPDATE CASCADE
  ,CONSTRAINT fk_imaf_reviewer FOREIGN KEY (assigned_reviewer_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ipca_manual_ai_proposals (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  finding_id BIGINT UNSIGNED NOT NULL,
  book_version_id BIGINT UNSIGNED NOT NULL,
  section_id BIGINT UNSIGNED NOT NULL,
  block_id BIGINT UNSIGNED NOT NULL,
  source_fingerprint CHAR(64) NOT NULL,
  expected_block_hash CHAR(64) NOT NULL,
  current_text MEDIUMTEXT NOT NULL,
  proposed_text MEDIUMTEXT NOT NULL,
  proposed_payload_json JSON NOT NULL,
  proposal_hash CHAR(64) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'pending',
  applied_at DATETIME NULL,
  applied_by INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_imaprop_finding_block (finding_id, block_id),
  KEY idx_imaprop_version_status (book_version_id, status),
  CONSTRAINT fk_imaprop_finding FOREIGN KEY (finding_id) REFERENCES ipca_manual_ai_findings(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_imaprop_version FOREIGN KEY (book_version_id) REFERENCES ipca_publishing_book_versions(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_imaprop_section FOREIGN KEY (section_id) REFERENCES ipca_publishing_book_sections(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_imaprop_block FOREIGN KEY (block_id) REFERENCES ipca_publishing_book_blocks(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_imaprop_applied_by FOREIGN KEY (applied_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ipca_manual_ai_decisions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  project_id BIGINT UNSIGNED NOT NULL,
  finding_id BIGINT UNSIGNED NULL,
  requirement_id BIGINT UNSIGNED NULL,
  decision VARCHAR(24) NOT NULL COMMENT 'approved | rejected | deferred | accepted',
  note TEXT NULL,
  decided_by INT NOT NULL,
  decided_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_imad_finding (finding_id),
  UNIQUE KEY uk_imad_requirement (requirement_id),
  KEY idx_imad_project (project_id, decided_at),
  CONSTRAINT fk_imad_project FOREIGN KEY (project_id) REFERENCES ipca_manual_ai_projects(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_imad_finding FOREIGN KEY (finding_id) REFERENCES ipca_manual_ai_findings(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_imad_requirement FOREIGN KEY (requirement_id) REFERENCES ipca_manual_ai_requirements(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_imad_user FOREIGN KEY (decided_by) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ipca_manual_ai_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  project_id BIGINT UNSIGNED NOT NULL,
  job_type VARCHAR(32) NOT NULL DEFAULT 'analysis',
  idempotency_key CHAR(64) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'queued' COMMENT 'queued | running | completed | retry | failed',
  attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
  max_attempts INT UNSIGNED NOT NULL DEFAULT 3,
  progress_percent TINYINT UNSIGNED NOT NULL DEFAULT 0,
  lease_token CHAR(36) NULL,
  lease_expires_at DATETIME NULL,
  available_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ai_run_id VARCHAR(191) NULL,
  result_json JSON NULL,
  error_message TEXT NULL,
  created_by INT NULL,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_imaj_idempotency (idempotency_key),
  KEY idx_imaj_claim (status, available_at, lease_expires_at),
  KEY idx_imaj_project (project_id, created_at),
  CONSTRAINT fk_imaj_project FOREIGN KEY (project_id) REFERENCES ipca_manual_ai_projects(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_imaj_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
