#!/usr/bin/env bash
# Sync allowlisted analytics secrets from PHP-FPM pool → /etc/ipca/analytics.env
#
# Root-only. Does not modify PHP-FPM configuration.
# Does not write secrets into the repository.
# Never echoes secret values.
#
# Usage:
#   sudo PHP_FPM_POOL=/etc/php/8.3/fpm/pool.d/www.conf \
#     scripts/analytics/sync_analytics_env_from_fpm.sh
set -euo pipefail

PHP_FPM_POOL="${PHP_FPM_POOL:-/etc/php/8.3/fpm/pool.d/www.conf}"
OUT_FILE="${IPCA_ANALYTICS_ENV_FILE:-/etc/ipca/analytics.env}"
OUT_DIR="$(dirname "$OUT_FILE")"

fail() {
  printf 'analytics env sync error: %s\n' "$1" >&2
  exit 1
}

[[ "$(id -u)" -eq 0 ]] || fail "must run as root"
[[ -r "$PHP_FPM_POOL" ]] || fail "PHP_FPM_POOL not readable: $PHP_FPM_POOL"

# Allowlist only — refuse anything else.
ALLOWLIST=(
  CW_OPENAI_API_KEY
  CW_OPENAI_MODEL
  CW_OPENAI_ASR_MODEL
  CW_DB_HOST
  CW_DB_PORT
  CW_DB_NAME
  CW_DB_USER
  CW_DB_PASS
)

extract_env() {
  local name="$1"
  local matches count value
  case "$name" in
    CW_OPENAI_API_KEY|CW_OPENAI_MODEL|CW_OPENAI_ASR_MODEL|CW_DB_HOST|CW_DB_PORT|CW_DB_NAME|CW_DB_USER|CW_DB_PASS)
      ;;
    *)
      fail "refusing non-allowlisted variable: $name"
      ;;
  esac

  matches="$(awk -v name="$name" '
    BEGIN { pattern = "^[[:space:]]*env\\[" name "\\][[:space:]]*=[[:space:]]*" }
    $0 ~ pattern {
      sub(pattern, "", $0)
      sub(/[[:space:]]*;[[:space:]]*$/, "", $0)
      print
    }
  ' "$PHP_FPM_POOL")"

  count="$(printf '%s\n' "$matches" | sed '/^$/d' | wc -l | tr -d ' ')"
  if [[ "$count" == "0" ]]; then
    return 1
  fi
  if [[ "$count" != "1" ]]; then
    fail "$name must be defined exactly once in PHP-FPM pool"
  fi
  value="$(printf '%s\n' "$matches" | sed '/^$/d')"
  # Strip surrounding quotes for storage consistency
  value="${value%\"}"
  value="${value#\"}"
  value="${value%\'}"
  value="${value#\'}"
  if [[ -z "$value" ]]; then
    fail "$name is empty in PHP-FPM pool"
  fi
  if [[ "$value" == EV\[* ]]; then
    fail "$name is EV[...] ciphertext in PHP-FPM pool — refusing"
  fi
  printf '%s' "$value"
}

mkdir -p "$OUT_DIR"
umask 077
tmp="$(mktemp "$OUT_DIR/.analytics.env.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Generated by scripts/analytics/sync_analytics_env_from_fpm.sh"
  echo "# Source pool: $PHP_FPM_POOL"
  echo "# Do not commit. Root-readable only."
  echo "# Regenerated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
} >"$tmp"

synced=0
missing=0
for name in "${ALLOWLIST[@]}"; do
  if value="$(extract_env "$name")"; then
    # Write KEY=VALUE without echoing value to stdout/logs
    printf '%s=%s\n' "$name" "$value" >>"$tmp"
    echo "$name: SYNCED"
    synced=$((synced + 1))
  else
    echo "$name: ABSENT_IN_FPM"
    missing=$((missing + 1))
  fi
done

install -m 600 -o root -g root "$tmp" "$OUT_FILE"
trap - EXIT
rm -f "$tmp"

echo "Wrote $OUT_FILE (mode 600). synced=$synced absent=$missing"
echo "PHP-FPM pool was not modified."
echo "Next: scripts/analytics/run-with-analytics-env.sh analytics/.venv/bin/python analytics/etl/runtime_preflight.py"
