<?php
declare(strict_types=1);

require_once __DIR__ . '/../src/AuditEventService.php';

/** @var array{code:string,name:string,description:string,exercise:array<string,mixed>} $missionDefinition */
$missionDefinition = require __DIR__ . '/mission_canonical/mission_2_1_5.php';
$exercise = $missionDefinition['exercise'];

function mission_canonical_sql_quote(string $value): string
{
    return "'" . str_replace("'", "''", $value) . "'";
}

$exerciseJson = AuditEventService::jsonEncode($exercise);
$scenarioJson = AuditEventService::jsonEncode($exercise['scenario_plan']);
$rubricJson = AuditEventService::jsonEncode($exercise['evaluation_rubric']);
$scenarioSource = $exercise['source']['scenario'];
$evaluationSource = $exercise['source']['evaluation'];
$scenarioHash = hash('sha256', $scenarioJson);
$rubricHash = hash('sha256', $rubricJson);

$lines = array(
    '-- Canonical mission 2-1-5 scenario plan and evaluation rubric.',
    '-- Generated by scripts/emit_mission_2_1_5_canonical_sql.php',
    '-- Run this file in MySQL. Do NOT run scripts/seed_mission_2_1_5_canonical.php in a SQL client.',
    '',
    'SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;',
    'SET collation_connection = utf8mb4_unicode_ci;',
    '',
    'SET @mission_code := ' . mission_canonical_sql_quote($missionDefinition['code']) . ';',
    'SET @mission_name := ' . mission_canonical_sql_quote($missionDefinition['name']) . ';',
    'SET @mission_description := ' . mission_canonical_sql_quote($missionDefinition['description']) . ';',
    'SET @exercise_json := CAST(' . mission_canonical_sql_quote($exerciseJson) . ' AS JSON);',
    '',
    'INSERT INTO ipca_missions (mission_uuid, organization_id, code, name, status)',
    "VALUES (UUID(), 1, @mission_code, @mission_name, 'active')",
    "ON DUPLICATE KEY UPDATE name = VALUES(name), status = 'active', updated_at = CURRENT_TIMESTAMP(3);",
    '',
    'SET @mission_id := (',
    '  SELECT id FROM ipca_missions',
    '  WHERE organization_id = 1 AND code COLLATE utf8mb4_unicode_ci = @mission_code COLLATE utf8mb4_unicode_ci',
    '  LIMIT 1',
    ');',
    '',
    'SET @current_version_id := (',
    '  SELECT current_version_id FROM ipca_missions WHERE id = @mission_id LIMIT 1',
    ');',
    '',
    'SET @already_canonical := (',
    '  SELECT CASE',
    '    WHEN @current_version_id IS NULL THEN 0',
    "    WHEN JSON_UNQUOTE(JSON_EXTRACT(exercise_json, '$.schema_version')) = 'ipca.mission.exercise.v2'",
    "      AND JSON_EXTRACT(exercise_json, '$.scenario_plan') IS NOT NULL",
    "      AND JSON_EXTRACT(exercise_json, '$.evaluation_rubric') IS NOT NULL",
    '    THEN 1 ELSE 0',
    '  END',
    '  FROM ipca_mission_versions',
    '  WHERE id = @current_version_id',
    '  LIMIT 1',
    ');',
    '',
    'SET @next_version_number := (',
    '  SELECT COALESCE(MAX(version_number), 0) + 1 FROM ipca_mission_versions WHERE mission_id = @mission_id',
    ');',
    '',
    'INSERT INTO ipca_mission_versions',
    '  (mission_id, mission_version_uuid, version_number, code_snapshot, name_snapshot, description, exercise_json, created_by)',
    'SELECT',
    '  @mission_id,',
    '  UUID(),',
    '  @next_version_number,',
    '  @mission_code,',
    '  @mission_name,',
    '  @mission_description,',
    '  @exercise_json,',
    '  NULL',
    'WHERE COALESCE(@already_canonical, 0) = 0;',
    '',
    'SET @version_id := CASE',
    '  WHEN COALESCE(@already_canonical, 0) = 1 THEN @current_version_id',
    '  ELSE LAST_INSERT_ID()',
    'END;',
    '',
    'UPDATE ipca_missions',
    'SET current_version_id = @version_id, updated_at = CURRENT_TIMESTAMP(3)',
    'WHERE id = @mission_id',
    '  AND @version_id IS NOT NULL',
    '  AND @version_id > 0;',
    '',
    'INSERT INTO ipca_mission_aliases (mission_id, alias, source)',
    "VALUES (@mission_id, @mission_code, 'mission_canonical_seed')",
    'ON DUPLICATE KEY UPDATE mission_id = VALUES(mission_id), source = VALUES(source);',
    '',
    'INSERT INTO ipca_mission_canonical_documents',
    '  (document_uuid, mission_version_id, document_type, schema_version, source_document,',
    '   source_revision, source_date, content_sha256, content_json)',
    'SELECT',
    '  UUID(),',
    '  @version_id,',
    "  'scenario_plan',",
    "  'scenario.v1',",
    '  ' . mission_canonical_sql_quote((string)$scenarioSource['document']) . ',',
    '  ' . mission_canonical_sql_quote((string)$scenarioSource['revision']) . ',',
    '  ' . mission_canonical_sql_quote((string)$scenarioSource['date']) . ',',
    '  ' . mission_canonical_sql_quote($scenarioHash) . ',',
    '  CAST(' . mission_canonical_sql_quote($scenarioJson) . ' AS JSON)',
    'WHERE @version_id IS NOT NULL',
    '  AND @version_id > 0',
    '  AND NOT EXISTS (',
    '    SELECT 1 FROM ipca_mission_canonical_documents',
    "    WHERE mission_version_id = @version_id AND document_type = 'scenario_plan'",
    '  );',
    '',
    'INSERT INTO ipca_mission_canonical_documents',
    '  (document_uuid, mission_version_id, document_type, schema_version, source_document,',
    '   source_revision, source_date, content_sha256, content_json)',
    'SELECT',
    '  UUID(),',
    '  @version_id,',
    "  'evaluation_rubric',",
    "  'rubric.v1',",
    '  ' . mission_canonical_sql_quote((string)$evaluationSource['document']) . ',',
    '  ' . mission_canonical_sql_quote((string)$evaluationSource['revision']) . ',',
    '  ' . mission_canonical_sql_quote((string)$evaluationSource['date']) . ',',
    '  ' . mission_canonical_sql_quote($rubricHash) . ',',
    '  CAST(' . mission_canonical_sql_quote($rubricJson) . ' AS JSON)',
    'WHERE @version_id IS NOT NULL',
    '  AND @version_id > 0',
    '  AND NOT EXISTS (',
    '    SELECT 1 FROM ipca_mission_canonical_documents',
    "    WHERE mission_version_id = @version_id AND document_type = 'evaluation_rubric'",
    '  );',
    '',
);

$outputPath = __DIR__ . '/sql/2026_07_29_seed_mission_2_1_5_canonical.sql';
file_put_contents($outputPath, implode(PHP_EOL, $lines));
fwrite(STDOUT, 'Wrote ' . $outputPath . PHP_EOL);
