<?php
declare(strict_types=1);

/**
 * Emit MySQL for bulk insert of courses → lessons → slides from a Kings-style manifest,
 * mirroring public/admin/import_lab.php when AI is off and page_count comes from the
 * manifest "lessons" array (not CDN probing).
 *
 * Usage:
 *   php scripts/generate_manifest_import_sql.php \
 *     --manifest=public/assets/kings_instrument_labs_manifest.json \
 *     --program=instrument \
 *     --out=scripts/sql/instrument_manifest_seed.sql
 *
 * Requires: programs row with program_key = instrument (script does not INSERT programs).
 */

require_once __DIR__ . '/../src/helpers.php';

$opts = getopt('', ['manifest:', 'program:', 'out:', 'template:']);
$manifestPath = $opts['manifest'] ?? (__DIR__ . '/../public/assets/kings_instrument_labs_manifest.json');
$programKey = $opts['program'] ?? 'instrument';
$outPath = $opts['out'] ?? (__DIR__ . '/sql/instrument_manifest_seed.sql');
$defaultTpl = $opts['template'] ?? 'MEDIA_LEFT_TEXT_RIGHT';

$raw = file_get_contents($manifestPath);
if ($raw === false) {
    fwrite(STDERR, "Cannot read manifest: {$manifestPath}\n");
    exit(1);
}
$data = json_decode($raw, true);
if (!is_array($data) || empty($data['labs']) || !is_array($data['labs'])) {
    fwrite(STDERR, "Invalid manifest JSON (need labs[])\n");
    exit(1);
}

$pageByLesson = [];
foreach ($data['lessons'] ?? [] as $row) {
    if (!is_array($row)) {
        continue;
    }
    $lid = (int)($row['lessonId'] ?? $row['lesson_id'] ?? 0);
    if ($lid <= 0) {
        continue;
    }
    $pageByLesson[$lid] = max(0, (int)($row['pages'] ?? 0));
}

$sqlEsc = static function (string $s): string {
    return str_replace(["\\", "'"], ["\\\\", "''"], $s);
};

$lines = [];
$lines[] = '-- Generated by scripts/generate_manifest_import_sql.php';
$lines[] = '-- Source: ' . $manifestPath;
$lines[] = '-- Program key: ' . $programKey;
$lines[] = '-- Default slide template: ' . $defaultTpl;
$lines[] = '';
$lines[] = 'SET NAMES utf8mb4;';
$lines[] = 'SET @program_id := (SELECT id FROM programs WHERE program_key = ' . "'" . $sqlEsc($programKey) . "'" . ' LIMIT 1);';
$lines[] = '-- If @program_id is NULL, add the program row before running the rest.';
$lines[] = '';

$lines[] = 'START TRANSACTION;';
$lines[] = '';

$labOrder = 10;
foreach ($data['labs'] as $lab) {
    if (!is_array($lab)) {
        continue;
    }
    $labId = (int)($lab['labId'] ?? 0);
    $lessonIds = $lab['lessonIds'] ?? $lab['lesson_ids'] ?? [];
    if ($labId <= 0 || !is_array($lessonIds) || $lessonIds === []) {
        continue;
    }

    $lessonIds = array_values(array_map('intval', array_filter($lessonIds, 'is_numeric')));
    if ($lessonIds === []) {
        continue;
    }

    $courseTitle = 'Lab ' . $labId;
    $courseSlug = slugify($courseTitle);
    $courseOrder = $labOrder;

    $lines[] = '-- Course external_lab_id=' . $labId;
    $lines[] = 'INSERT INTO courses (program_id, title, slug, revision, sort_order, is_published, external_lab_id)';
    $lines[] = 'VALUES (@program_id, '
        . "'" . $sqlEsc($courseTitle) . "', "
        . "'" . $sqlEsc($courseSlug) . "', "
        . "'1.0', "
        . (int)$courseOrder . ', '
        . '0, '
        . (int)$labId
        . ') ON DUPLICATE KEY UPDATE '
        . 'title = VALUES(title), '
        . 'sort_order = VALUES(sort_order), '
        . 'external_lab_id = VALUES(external_lab_id);';
    $lines[] = '';

    $sort = 10;
    foreach ($lessonIds as $extLessonId) {
        $extLessonId = (int)$extLessonId;
        $pageCount = (int)($pageByLesson[$extLessonId] ?? 0);
        $lessonTitle = 'Lesson ' . $extLessonId;

        $lines[] = 'INSERT INTO lessons (course_id, external_lesson_id, title, sort_order, page_count, default_template_key)';
        $lines[] = 'SELECT c.id, '
            . $extLessonId . ", "
            . "'" . $sqlEsc($lessonTitle) . "', "
            . (int)$sort . ', '
            . (int)$pageCount . ", "
            . "'" . $sqlEsc($defaultTpl) . "' "
            . 'FROM courses c '
            . 'WHERE c.program_id = @program_id AND c.slug = ' . "'" . $sqlEsc($courseSlug) . "'" . ' '
            . 'LIMIT 1 '
            . 'ON DUPLICATE KEY UPDATE '
            . 'title = VALUES(title), '
            . 'sort_order = VALUES(sort_order), '
            . 'page_count = VALUES(page_count), '
            . 'default_template_key = VALUES(default_template_key);';
        $lines[] = '';

        if ($pageCount > 0) {
            for ($p = 1; $p <= $pageCount; $p++) {
                $imgPath = image_path_for($programKey, $extLessonId, $p);
                $lines[] = 'INSERT INTO slides (lesson_id, page_number, template_key, image_path)';
                $lines[] = 'SELECT l.id, ' . (int)$p . ", "
                    . "'" . $sqlEsc($defaultTpl) . "', "
                    . "'" . $sqlEsc($imgPath) . "' "
                    . 'FROM lessons l '
                    . 'INNER JOIN courses c ON c.id = l.course_id AND c.program_id = @program_id '
                    . 'WHERE c.slug = ' . "'" . $sqlEsc($courseSlug) . "' "
                    . 'AND l.external_lesson_id = ' . $extLessonId . ' '
                    . 'LIMIT 1 '
                    . 'ON DUPLICATE KEY UPDATE '
                    . 'template_key = VALUES(template_key), '
                    . 'image_path = VALUES(image_path);';
                $lines[] = '';
            }
        }

        $sort += 10;
    }

    $labOrder += 10;
}

$lines[] = 'COMMIT;';

$dir = dirname($outPath);
if (!is_dir($dir)) {
    mkdir($dir, 0755, true);
}
file_put_contents($outPath, implode("\n", $lines) . "\n");

fwrite(STDOUT, "Wrote {$outPath}\n");
